import os
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
from reportlab.lib.units import inch

def generate_forensics_pdf(report_data: dict, output_path: str):
    """
    Generates a professional forensics PDF report using ReportLab.
    """
    doc = SimpleDocTemplate(output_path, pagesize=A4)
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor("#06b6d4"),
        alignment=1,
        spaceAfter=20
    )
    
    header_style = ParagraphStyle(
        'HeaderStyle',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor("#334155"),
        spaceBefore=12,
        spaceAfter=6
    )
    
    story = []
    
    # Title
    story.append(Paragraph("FakeLineage Forensics Report", title_style))
    story.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
    story.append(Spacer(1, 0.2*inch))
    
    # Summary Table
    verdict = report_data.get("verdict", "PENDING")
    v_color = colors.green
    if verdict == "DEEPFAKE": v_color = colors.red
    elif verdict == "MANIPULATED": v_color = colors.orange
    elif verdict == "SUSPICIOUS": v_color = colors.yellow
    
    summary_data = [
        ["Report ID:", report_data.get("report_id", "N/A")],
        ["Image ID:", report_data.get("image_id", "N/A")],
        ["Final Verdict:", verdict],
        ["Authenticity Score:", f"{report_data.get('overall_authenticity_score', 0):.2%}"]
    ]
    
    t = Table(summary_data, colWidths=[1.5*inch, 4*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (1, 0), colors.whitesmoke),
        ('TEXTCOLOR', (1, 2), (1, 2), v_color),
        ('FONTNAME', (1, 2), (1, 2), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.3*inch))
    
    # Deepfake Analysis Breakdown
    story.append(Paragraph("Deepfake Analysis Breakdown", header_style))
    df = report_data.get("deepfake_analysis", {})
    df_data = [
        ["Signal", "Score", "Indication"],
        ["Overall AI Score", f"{df.get('overall_score', 0):.2%}", "High" if df.get('is_deepfake') else "Low"],
        ["ELA (Error Level)", f"{df.get('ela_score', 0):.2%}", "Anomaly" if df.get('ela_score', 0) > 0.4 else "Normal"],
        ["GAN Fingerprints", f"{df.get('gan_artifact_score', 0):.2%}", "Detected" if df.get('gan_artifact_score', 0) > 0.4 else "Clean"],
        ["Face-swap Logic", f"{df.get('face_swap_score', 0):.2%}", "Suspicious" if df.get('face_swap_score',0) > 0.5 else "Natural"],
        ["Noise Floor", f"{df.get('noise_inconsistency', 0):.2%}", "Inconsistent" if df.get('noise_inconsistency', 0) > 0.4 else "Uniform"]
    ]
    
    dt = Table(df_data, colWidths=[1.8*inch, 1.2*inch, 2.5*inch])
    dt.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('ALIGN', (1, 0), (1, -1), 'CENTER'),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(dt)
    story.append(Spacer(1, 0.3*inch))
    
    # Evidence Summary
    story.append(Paragraph("Forensic Evidence Brief", header_style))
    for ev in report_data.get("evidence_summary", []):
        story.append(Paragraph(f"• {ev}", styles['Normal']))
    story.append(Spacer(1, 0.3*inch))
    
    # Metadata
    story.append(Paragraph("Metadata & Technical Specs", header_style))
    meta = report_data.get("metadata_analysis", {})
    meta_data = [
        ["Format:", meta.get("format", "Unknown")],
        ["Dimensions:", f"{meta.get('width', 0)} x {meta.get('height', 0)}"],
        ["Camera Make:", meta.get("make", "N/A")],
        ["Steganography:", "DETECTED" if meta.get("steganography_detected") else "None Found"]
    ]
    mt = Table(meta_data, colWidths=[1.5*inch, 4*inch])
    mt.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('PADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(mt)
    
    # Footer
    story.append(Spacer(1, 1*inch))
    story.append(Paragraph("This document is an automated forensic report generated by FakeLineage Engine.", styles['Italic']))
    story.append(Paragraph("Classification: CONFIDENTIAL / INVESTIGATIVE", styles['Normal']))

    doc.build(story)
